#!/bin/sh
# Unitary tests for Journal
# We can't write unit tests for interactive behaviour interacting with external software.
# But we can compare commands strings for a range of inputs to see if they match with what we expect.
todoPath="../sample"
logPath="../sample/log"

# ----- #
# TASKS #
# ----- #
if ! [ -d "$todoPath" ]; then
    printf "TODOs path is missing. Critical!\n"
    exit 1
else
    # shellcheck disable=SC2164
    cd "$todoPath"
fi

# PRINT
## expected
## actual
## pass?

# SHOW

# FIND

# COMMIT (later)

# --- #
# LOG #
# --- #
if ! [ -d "$logPath" ]; then
    printf "Logs path is missing. Critical!\n"
    exit 1
else
    # shellcheck disable=SC2164
    cd "$logPath"
fi

# WRITE (later)

# READ (later)

# ROTATE (later)
