#!/bin/sh
# Unitary tests for Journal
# We can't write unit tests for interactive behaviour interacting with external software.
# But we can compare commands strings for a range of inputs to see if they match with what we expect.

# print

# show

# find

# commit

# write

# read

# rotate
