#!/bin/bash
# Tool to manage a markdown diary

root="$HOME/Workshop/diary"
daily=$(date '+%y-%m-%d' -d "-30days") # retention target for daily entries
monthly=$(date '+%y-%m-%d' -d "-6months") # retention target for monthly entries
today=$(date '+%y-%m-%d').md

cd "$root" || exit

function editToday {
    echo -e "### $(date '+%H:%M')\n" >> "$today"
	$EDITOR "$today" 
}

function readDiary {
	rg -t md --files | fzf --preview "bat --color always -pp --wrap character --terminal-width $(( $(tput cols) / 2 - 4)) -l md -r :500 {}" # $COLUMNS isn't working reliably
}

function cleanDiary {
	for f in $(ls [0-9][0-9]-[0-9][0-9]-[0-9][0-9].md 2>/dev/null); do # daily
		if [[ ${f:0:8} < $daily ]]; then
			echo -e "Moved \e[31m$f\e[0m to \e[32m${f:0:5}.md\e[0m"
			{ 	echo -e "## $(date '+%d de %B' -d "${f:0:8}")"
				cat "$f" && echo -e "\n"
			} >> "${f:0:5}.md"
			rm "$f"
		fi
	done

	for f in $(ls [0-9][0-9]-[0-9][0-9].md 2>/dev/null); do # monthly
		if [[ ${f:0:5} < $monthly ]]; then
			echo -e "Moved \e[31m$f\e[0m to \e[32m${f:0:2}.md\e[0m"
			{ 	echo -e "# $(date '+%Y' -d "${f:0:5}")"
				cat "$f" && echo -e "\n"
			} >> "${f:0:2}.md"
			rm "$f"
		fi
	done	
}

case $1 in
	write) editToday; exit 0;;
	read) readDiary; exit 0;;
	clean) cleanDiary; exit 0;; 
esac

(echo -e "HELP:
\t\e[1m'write'\e[0m create/edit today's entry;
\t\e[1m'read'\e[0m fuzzy search among entries; 
\t\e[1m'clean'\e[0m merge entries in monthly and yearly entries following a retention policy." && exit)

