#!/bin/bash
# For use with FZF, output a preview of the file with the selected line somewhat centered.
# $LINES and $COLUMNS is the size of the preview window from the fzf env. 1st argument is file name and 2nd argument is line number.

t=$(( LINES / 2 )) # threshold
s=$(( $2 - t )) && [ $s -lt 1 ] && s=1 # start line w/ failsafe
e=$(( $2 + t )) # end line
bat --color always -l md --terminal-width $COLUMNS --highlight-line "$2" -r $s:$e -pp "$1"

