#!/bin/bash

# This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License v3 as published by the Free Software Foundation.
# It is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with it. If not, see <https://www.gnu.org/licenses/>.

# Output a preview of the file with the selected line somewhat centered. $LINES and $COLUMNS is the size of the preview window from the fzf env.
# $1 is function, $2 is file name, $3 is line number and $4 is task description.

function previewNote {
	t=$(( LINES / 2 )) # threshold
	s=$(( $2 - t )) && [ $s -lt 1 ] && s=1 # start line w/ failsafe
	e=$(( $2 + t )) # end line
	#c=$(( $(tput cols) / 2 - 4 )) # $COLUMNS isn't working reliably
	#bat --color always -l md --wrap character --terminal-width $c --highlight-line "$2" -r $s:$e -pp "$1"
	bat --color always -l md --highlight-line "$2" -r $s:$e -pp "$1" # wraping is being done in fzf now
}

function cyclePriority {
	echo "$3" | rg "\+asap" >/dev/null && sed -i "$2s/\+asap/\+done/" "$1" && return 0
	echo "$3" | rg "\+done" >/dev/null && sed -i "$2s/\+done/\+later/" "$1" && return 0
	echo "$3" | rg "\+later" >/dev/null && sed -i "$2s/\+later/\+asap/" "$1" && return 0
}

function deleteTask {
	del=$2 && del+=d
	sed -i "$del" "$1"
}

case $1 in
	preview) previewNote "$2" "$3";;
	cycle) cyclePriority "$2" "$3" "$4";;
	delete) deleteTask "$2" "$3";;
	print) journal print;; # a hack as subshell can't invoke parent functions
esac

exit 0

