#!/bin/bash

# This is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License v3 as published by the Free Software Foundation.
# It is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with it. If not, see <https://www.gnu.org/licenses/>.

## CONFIG ##
# Set general defaults
root_dir="$HOME"
log_dir="$HOME/Docs/log"
ignore="$XDG_CONFIG_HOME/journal/ignore"
daily=$(date '+%y-%m-%d' -d "-7days") # retention target for daily entries
monthly=$(date '+%y-%m-%d' -d "-3months") # retention target for monthly entries

# Set colors defaults
reset=$(printf '\033[0m')
gray=$(printf '\033[2;20m')
bold_blue=$(printf '\033[1;34m')
red=$(printf '\033[31m')
green=$(printf '\033[32m')
magenta=$(printf '\033[35m')
cyan=$(printf '\033[36m')
yellow=$(printf '\033[33m')
blue=$(printf '\033[34m')

# Load user configuration
config_file="$XDG_CONFIG_HOME/journal/config"
#shellcheck disable=SC1090
[ -f "$config_file" ] && source "$config_file"

# Testing mode
# Overrides conf for unit testing if $journalTesting=true
# shellcheck disable=SC2154
if [ "$journalTesting" = "true" ]; then
    root_dir="sample"
    log_dir="sample/log"
    unset ignore
    if ! { [ -d "$root_dir" ] && [ -d "$log_dir" ]; }; then
       echo "Expected dirs weren't found!" && exit 1 
    fi
fi

# Set editor
# Use $editor from config, otherwise, use $EDITOR, if defined, or whatever is available.
if ! [ "$editor" ]; then
    editors=(vi vim nvim nano)
    # shellcheck disable=SC2153
    if [ "$EDITOR" ]; then
        editor=$EDITOR
    else
        for prog in "${editors[@]}"; do
            if [ "$(command -v "$prog")" ]; then
                # remove alias and path prefix
                editor=$(command -v "$prog" | sed 's/alias .*=//;s#.*/##')
            fi
        done
    fi
fi

# Open vim and jump to given line (to use with fzf)
# shellcheck disable=SC2001
editor_jump_to_line=$(sed "s/vim/vim {1} -c '{2} normal zz'/" <<< "$editor")

## HELP ##
# Show help if no valid argument is parsed
printHelp() {
    echo -e "HELP:
    TODOs:
    \t\e[1m'print'\e[0m print todo tasks to stdout in plain text;
    \t\e[1m'show'\e[0m show tasks in a pager with pretty formatting, use -a to display parked tasks;
    \t\e[1m'find'\e[0m show tasks in fzf with note preview. f1 opens in editor, f2 cycles priority tags and f5 delete;
    \t\e[1m'commit'\e[0m write to journal and clean done tasks within files.;
    LOG:
    \t\e[1m'write'\e[0m create/edit log entry, use -d to do a daily review
    \t\e[1m'read'\e[0m fuzzy browse among entries; 
    \t\e[1m'rotate'\e[0m merge entries in monthly and yearly entries following the retention policy." && exit
}

## UTILS ##
_confirmDialog() {
# Subprocedure that asks for user confirmation
    # shellcheck disable=SC2162
	read -p "Are you sure? (y/N) " yn;
	case $yn in
		[Yy][Ee][Ss]|[Yy]) return 0;;
		[Nn][Oo]|[Nn]) return 1;;
		*) echo "Please answer yes or no." && return 1;;
	esac
}

## TASKS ##
cd "$root_dir" || exit 1
[ -d "$log_dir" ] || mkdir -p "$log_dir"

printTodos() { 
# Find TODOs on files and send as plain-text to STDOUT
# $1 is a [Rust RE](https://docs.rs/regex/1.3.9/regex/) rule
    re_string="$1"
	if [ "$re_string" ]; then
		rg -N --color never --no-heading -t md --ignore-file "$ignore" -e "$re_string"
	else
		rg -n --color never --no-heading -t md --ignore-file "$ignore" -e "TODO: "
	fi | sed 's/TODO: //;s/\r//' # delete todo preffix and carriage return escape code
}

_prettifyTodos() {
# Format and colorize plain-text TODOs from STDIN 
	sed 's/:/\n/' | awk '!x[$0]++' | # split & dedup
	sed "s/^.*\.md$/\n${bold_blue}&${reset}/;
        s/\+done/${green}&${reset}/;
        s/\+asap/${red}&${reset}/;
        s/\+later/${magenta}&${reset}/;
        s/[=!?].[^ ]*/${cyan}&${reset}/;
        s/\!.[^ ]*/${cyan}&${reset}/;
        s/#.[^ ]*/${yellow}&${reset}/;
        s/@.[^ ]*/${blue}&${reset}/" #colorize
}

printPrettyTodos() {
# Print pretty TODOs to STDOUT to browse with a pager
    while getopts ":a" option; do
      case $option in
        a) all_todos=True ;;
        ?) echo "Error: option -$OPTARG is not implemented";;
      esac
    done

	printTodos "^TODO:.*\+done.*$"  | _prettifyTodos
	printTodos "^TODO:.*\+asap.*$"  | _prettifyTodos
	printTodos "^TODO:.[^\+]*$"     | _prettifyTodos
	# only print those if -a flag is set
    [ $all_todos ] &&
    printTodos "^TODO:.*\+later.*$" | _prettifyTodos
}

_printDoneTodos() { 
#  Print done TODOs to STDOUT
	echo -e "## $(date "+%d de %B de %Y às %H:%M")"
	rg -N --color never --no-heading -t md --ignore-file "$ignore" -e "^TODO:.*\+done.*$" |
    sed 's/:/: /;s/\+done//' && echo -e ""
}

_deleteDoneTodos() {	
# Delete done TODOs within files
    local files && files=$(
        rg -N -t md --ignore-file "$ignore" -e "^TODO:.*\+done.*$" | # find done todos
        sed 's/:.*//' | # extract files
        awk '!x[$0]++' # remove duplicates
    )
	for file in $files; do # iterate over files
		sed -i '/\+done/d' "$file" # delete line with todo
	done
}

_commitGit() {
# Non-interactively commit changes in a Git repo
	local last_commit="git -C '$root_dir' log HEAD^..HEAD --pretty=format:'%s'" # find last commit
	local today && today=$(date "+%y-%m-%d") 
	git -C "$root_dir" add -A &&
    if [ "$today" = "$last_commit" ]; then
		git -C "$root_dir" commit --amend -m "$today" # amend if not first commit in the day
	else
		git -C "$root_dir" commit -m "$today" # do not amend otherwise
	fi
}

# Commit all done TODOs to a journaling
commitDoneTodos() {
    _confirmDialog && _printDoneTodos >> "journal.md" && _deleteDoneTodos && _commitGit
}

# FZF
fzfPrint() {
# Print TODOs for fzf
    printTodos |
    sed -E "s/(.*):([0-9]*):(.*)/${magenta}\1${reset}:${gray}\2${reset}:\3/"
}

fzfFind() {
# Invoke FZF to fuzzy find and preview TODOs context
# {1} is file name, {2} is line number and {3} is task description.
    fzfPrint |
    fzf --ansi --delimiter ':' \
        --preview "journal fzf-preview {1} {2}" \
        --preview-window=right:50%:wrap \
        --header "f1 → default, f2 → editor, f3 → cycle priority, del → delete" \
        --layout=reverse \
        --bind \
"f1:execute-silent(xdg-open {1} 2>/dev/null),\
f2:execute($editor_jump_to_line),\
f3:reload(journal fzf-cycle {1} {2} {3} && journal fzf-print),\
del:reload(journal fzf-delete {1} {2} && journal fzf-print)"
}

fzfPreview() {
# Output a preview of the file with the selected line somewhat centered.
# FZF env: $FZF_PREVIEW_LINES and $FZF_PREVIEW_COLUMNS is the size of the preview window.
    local file="$1"
    local line="$2"

    t=$(( FZF_PREVIEW_LINES / 2 )) # threshold
	s=$(( line - t )) && [ $s -lt 1 ] && s=1 # start line w/ failsafe
	e=$(( line + t )) # end line
	bat --color always -l md --highlight-line "$line" -r $s:$e -pp "$file" # wraping is being done in fzf now
}

fzfCycle() {
# Cycle between task priorities
    local file="$1"
    local line="$2"
    local task="$3"
    # check if priority tag exists in tasks and append +asap if not
    if ! rg '\+(asap|done|later)' <<< "$task" >/dev/null; then
        sed -i -E "${line}s/^(.*)$/\1 \+asap/" "$file" && return 0
    fi

    # cycle between priority tags otherwise
    rg "\+asap"  <<< "$task" >/dev/null && sed -i "${line}s/\+asap/\+done/" "$file" && return 0
    rg "\+done"  <<< "$task" >/dev/null && sed -i "${line}s/\+done/\+later/" "$file" && return 0
    rg "\+later" <<< "$task" >/dev/null && sed -i "${line}s/\+later//" "$file" && return 0
}

fzfDelete() {
	del=$2 && del+=d
	sed -i "$del" "$1"
}

## JOURNALING ##
writeLog() {
# Create a log entry with present date/time and open it with $EDITOR
    while getopts ":d" option; do
      case $option in
        d) daily_standup=True ;;
        ?) echo "Error: option -$OPTARG is not implemented";;
      esac
    done

    cd "$log_dir" || exit 1
    #now="$(date '+%y-%m-%dT-%H-%M').md"
    now="$(date '+%y-%m-%d').md"
    # insert line break if file exists
    [[ -f $now ]] && header="\n"
    header+="### $(date '+%H:%M')"
    # insert daily standup if flag if found
    [[ $daily_standup ]] && header+="
#### What did I accomplish yesterday?
#### What will I do today?
#### What obstacles are impeding my progress?\n"
    echo -e "$header" >> "$now"
	$EDITOR "$now" 
}

readLog() {
# Invoke FZF to fuzzy find and preview log entries
    cd "$log_dir" || exit 1
    fd '^[0-9]{2}.*.md$' |
    fzf --tac --no-sort \
        --layout=reverse \
        --preview "bat --color always -pp --wrap character --terminal-width $(( $(tput cols) / 2 - 4)) -l md -r :500 {}" \
        --header "f1 → default, f2 → editor, del → delete" \
        --bind "f1:execute-silent(xdg-open {} 2>/dev/null),f2:execute($editor {}),del:reload(trash {} && fd '^[0-9]{2}.*.md$')"
}

rotateLog() {
# Rotate old entries to monthly/yearly entries
    cd "$log_dir" || exit 1
    mapfile -t daily_entries < <(fd '^[0-9]{2}-[0-9]{2}-[0-9]{2}.*.md$')
	for entry in "${daily_entries[@]}"; do
		if [[ ${entry:0:8} < $daily ]]; then
			echo -e "Moved \e[31m$entry\e[0m to \e[32m${entry:0:5}.md\e[0m"
			{ 	echo -e "## $(date '+%B %d, %A' -d "${entry:0:8}")"
				cat "$entry" && echo -e "\n"
			} >> "${entry:0:5}.md"
			rm "$entry"
		fi
	done

    mapfile -t monthly_entries < <(fd '^[0-9]{2}-[0-9]{2}.md$')
	for entry in "${monthly_entries[@]}"; do
		if [[ ${entry:0:5} < $monthly ]]; then
			echo -e "Moved \e[31m$entry\e[0m to \e[32m${entry:0:2}.md\e[0m"
			{ 	echo -e "# $(date '+%Y' -d "${entry:0:5}")"
				cat "$entry" && echo -e "\n"
			} >> "${entry:0:2}.md"
			rm "$entry"
		fi
	done	
}

## SWITCHES ##
case $1 in
	print) printTodos;;
	show) printPrettyTodos "${@:2}" | less -R;;
    find) fzfFind;;
	commit) commitDoneTodos;;
	write) writeLog "${@:2}";;
	read) readLog;;
	rotate) rotateLog;;
    fzf-print) fzfPrint;;
	fzf-preview) fzfPreview "$2" "$3";;
	fzf-cycle) fzfCycle "$2" "$3" "$4";;
	fzf-delete) fzfDelete "$2" "$3";;
    *) printHelp;;
esac
