#!/bin/bash
# This prints an example of the markdown extended todo syntax

# Prior
#echo -e "\e[1mTODO:\e[0m \e[39mDo something.\e[0m \e[1;31m+\e[31masap\e[0m \e[1;32m+\e[32mdone\e[0m \e[1;35m+\e[35mlater\e[0m \e[1;34m@lbcnz\e[0m \e[1;33m#\e[33msystem\e[0m \e[1;36m=\e[36m20-07-15 >20-07-15 !20-07-15\e[0m"

# Current
reset='\e[0m'
bold='\e[1m'
red='\e[1;31m'
green='\e[1;32m'
magenta='\e[1;35m' 
blue='\e[1;34m'
yellow='\e[1;33m'

# shellcheck disable=SC2059
printf "${bold}TODO:${reset} Do something. ${red}+asap${reset} ${green}+done${reset} ${magenta}+later${reset} ${blue}@name${reset} ${yellow}#tag${reset}\n"
